In [19]:
import numpy as np


a = np.matrix([[2,1,0],[-1,0,-1],[0,1,2]])  #Nilai matriks 
print("Matriks")
print(a)

eigenvalue, eigenvektor= np.linalg.eig(a) #Untuk mendapatkan Eigen Value dan Eigen Vektor 
print("\nEigenvalue")
print (eigenvalue)
print("\nEigenvektor")
print (eigenvektor)


Matriks
[[ 2  1  0]
 [-1  0 -1]
 [ 0  1  2]]

Eigenvalue
[1.+1.j 1.-1.j 2.+0.j]

Eigenvektor
[[-3.53553391e-01-0.35355339j -3.53553391e-01+0.35355339j
  -7.07106781e-01+0.j        ]
 [ 7.07106781e-01+0.j          7.07106781e-01-0.j
  -8.67253443e-17+0.j        ]
 [-3.53553391e-01-0.35355339j -3.53553391e-01+0.35355339j
   7.07106781e-01+0.j        ]]
